### ISSUE TITLE
Add loveCount in Post and isLovedByMe in the /api/post GET API

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-express#13]
## Context
We allow to love post by `/api/post/:postId/love`. So now we need to show that in the `/api/post` GET API

## Task
- Count loves and add it as a field called `loveCount` in response of `getAllPostsWithCommentCount`. I think change the name of the method too 😅
- Add a new field `isLovedByMe` in the response.
- From token get user's username and check if the user in post's loves. If exists make `isLovedByMe` true, else false.

**Comment by alammoiz** [comment]
Please assign to me @Ananto30

**Comment by Ananto30** [comment]
Awesome! 🚀
