### ISSUE TITLE
Fix post to take only urls

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-express#2]
## Context
As we will only allow users to share links from now on, we will only take URL in `/api/post` POST request.

## Task
- `/api/post` takes `text` in body, change it to 'url`.
- Strictly verify it's a URL.
- Put some backlisted domains like adult sites, just use a local array. If `url` domain in this list, send a error message "Adult contents are not allowed".

**Comment by alammoiz** [comment]
Can you please elaborate more?
Are you talking about createPost API? 
@Ananto30

**Comment by Ananto30** [comment]
Yes, `createPost`. Let me elaborate more -

- `createPost` now takes `text` in body, replace that with `url`
- Verify that the `url` is only a valid URL, not other text or anything. We will only allow posting a URL or link like https://github.com/Ananto30/zero
- You also need to extract the domain from the URL/link. You can keep an array of adult sites locally, and check against them. If it falls into the adult category return error message "Adult contents are not allowed".

For now, you don't need to focus on saving, cause after this task https://github.com/Ananto30/golpo-express/issues/3 we will get the metadata from the URL and save it accordingly.

Is it more clear? @alammoiz  😃

And thanks a lot for your contributions 😃🙌

**Comment by alammoiz** [comment]
Yes make sense, Please assign it to me :) @Ananto30
