### ISSUE TITLE
Implement comment notificaiton

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-express#21]
## Context
We want to show notifications to users when someone comments on their post.

## Task
- Create Notification model containing -
    - post_id
    - username
    - comment_author
    - created_at
    - clicked
- When someone comments on a post, create a new `Notification` entry in db where `post_id` is the post where someone commented. `username` is whom's post someone commented. `comment_author` is the username of the commenter. `created_at` is the time.now() and `clicked` is false.
- Create an endpoint `/api/notification/:username` GET to get notifications of a user by username.
- Create an endpoint `/api/notification/:id/clicked` POST to make `clicked` true for the user. Please ensure that the token user and the clicked notification's `username` is same, otherwise throw error.

**Comment by ayeolakenny** [comment]
@Ananto30 assign this to me, looks interesting 🚀

**Comment by Ananto30** [comment]
Sure! Go on 🚀

**Comment by ayeolakenny** [comment]
@Ananto30 all done and tested you can review now 🚀
