### ISSUE TITLE
Implement chat seen endpoint /api/chat/:id/seen

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-express#22]
## Context
We want to show in frontend if the user has any chats unread. So we need an endpoint where user will send that he already seen that chat.

## Task
- Add new api `/api/chat/:receiver/:chatId/seen` in routes and controller. The api takes no `body`.
- Conversation model has a field called `seen`, implement a chatSeen function in conversation.service that store the chat id's seen true for the specific receiver. Get the sender user by token.

**Comment by alammoiz** [comment]
I want to do that, can you please assign it to me? @Ananto30

**Comment by Ananto30** [comment]
Thanks 🙏
