### ISSUE TITLE
Save author image with the post

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-express#26]
## Context
We want to show author image with the post.

## Task
- Add `author_image` in Post model.
- When creating the post add `author_image` from the `userMeta.image` or `user.google_picture`.

**Comment by MohsinNajmuddin** [comment]
@Ananto30 Fixed this issue. Raise the PR #32

**Comment by MohsinNajmuddin** [comment]
@Ananto30 addressed your review comments. Please review and merge
