### ISSUE TITLE
Extract metadata from url

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-express#3]
## Context
As we will move to only link sharing, we need to extract the link's content called "Link Preview".

## Task
- Add a method in `service/post.service.js` that will take parameter `url` and extract meta data from it.
- You can use libraries like https://www.npmjs.com/package/link-preview-js or follow tutorials like this - https://dev.to/orkhanjafarovr/generate-link-preview-cover-with-nodejs-22a
- We need at least these fields -
    - image
    - title
    - description
    - siteName
    - favicon
- If possible extract other relevant fields that can be used later.

**Comment by sagarchoudhary96** [comment]
@Ananto30  can you assign this to me ?

**Comment by Ananto30** [comment]
Sure! 👍

**Comment by sagarchoudhary96** [comment]
@Ananto30  created a PR
