### ISSUE TITLE
Add api/post/:postId/love to love a post

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-express#4]
## Context
We will allow users to love a post like Twitter.

## Task
- In `model/post.model.js` Post model add new array `loves`
- In `router/post.js` add new POST endpoint `/:postId/love`
- Endpoint will take nothing in the body
- Get the user by token
- Add the `username` in Post model in `service/post.service.js`

**Comment by alammoiz** [comment]
@Ananto30 I would love to do this task, Please assign it to me

**Comment by Ananto30** [comment]
Sure! 👍

**Comment by alammoiz** [comment]
@Ananto30 Created PR https://github.com/Ananto30/golpo-express/pull/5

**Comment by Ananto30** [comment]
Thanks @alammoiz for the awesome work!
