### ISSUE TITLE
Add tags in post

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-express#7]
## Context
As we will be allowing users to filter the posts with tags, we need to store tags somewhere and show them with the post to allow filtering in frontend.

## Task
- Make a list of tags (can be a local list in a constants.js file)
    - Music
    - Game
    - Nature
    - Calm
    - Funny
    - Startup
    - Life
    - Travel
    - Food
    - Entrepreneurship
    - Education
    - Health
    - Love
    - Design
    - Writing
    - Technology
    - Self-Improvement
    - Business
    - Sports
    - Art
    - Open-Source
    - Programming
- In `/model/post.model.js` Post model add `tags` list (list of strings, from above tags).
- In `/service/post.service.js` add `tags` from request body.
- Add a new endpoint `/api/post/tags` to list all the tags.

**Comment by Pervolarakis** [comment]
can i have this one?

**Comment by Ananto30** [comment]
Sure! 👍
